#配置模板
#https://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/html/common-application-properties.html
spring:
  http:
    multipart:
      enabled: true
      max-file-size: 9999MB
      max-request-size: 9999MB
  #模板配置
  thymeleaf:
    #开发时一定关闭，否则调试困难
    cache: false
    prefix: classpath:/static/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhice?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
#    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
#      use-new-id-generator-mappings: true
    show-sql: true
server:
  context-path: /zhice